#!/bin/bash
###############################################################################
# AppTheShelf
# Elegant LXC remote container management
#
# Copyright:
# Stefan Koch <stefkoch@posteo.de>
#
# License: GPLv3
###############################################################################

while read line;
do
    varnm=$(echo "$line" | awk -F= '{print $1}')
    value=$(echo "$line" | awk -F= '{print $2}')
    eval "$varnm=$value"
done< <(cat "$rc" | grep -v -e '^#' -e '^$' -e '(' -e ')' -e '`' -e '\[')
