#!/bin/bash
###############################################################################
# AppTheShelf
# Elegant LXC remote container management
#
# Copyright:
# Stefan Koch <stefkoch@posteo.de>
#
# License: GPLv3
###############################################################################

appID=$(getAppID "$name")
if [ "$appID" != "" ]; then
    echo "name already used"
    exit 1
fi
if [ "$extport" = "" ]; then
    extport="none"
fi
if [ "$intport" = "" ]; then
    intport="none"
fi
if [ "$guestdir" = "" ]; then
    guestdir="none"
fi
if [ "$webspec" = "" ]; then
    webspec="none"
fi
echo "Create new app ($name)"
execute create "$name" $extport $intport "$guestdir" "$webspec"
