#!/bin/bash


echo "Available Profiles:"
echo ""

for prof in $avail_profiles;
do
    eval "user=\$${prof}_user"
    eval "host=\$${prof}_host"
    echo " [$prof]  -  $user@$host"
done
echo ""
echo " Default Profile: $default_default"
