#!/bin/bash
###############################################################################
# AppTheShelf
# Elegant LXC remote container management
#
# Copyright:
# Stefan Koch <stefkoch@posteo.de>
#
# License: GPLv3
###############################################################################

appID=$(getAppID "$name")
if [ "$appID" != "" ]; then
    echo "name already used"
    exit 1
fi
echo "Create new app ($name)"
execute create $name $extport $intport
