#!/bin/bash
appID=$(getAppID "$name")
if [ "$appID" = "" ]; then
    echo "app not found"
    exit 1
fi
port="$(execute getport $appID)"
echo "[apps]"
echo "$name ansible_port=$port ansible_host=$host"
