#!/bin/bash
###############################################################################
# AppTheShelf
# Elegant LXC remote container management
#
# Copyright:
# Stefan Koch <stefkoch@posteo.de>
#
# License: GPLv3
###############################################################################

if [ "$filter" = "" ]; then
    execute listfw
else
    execute listfw $filter
fi
