#!/bin/bash 

name="$1"

cd /var/lib/lxc

if [ ! -d "$name" ]; then
	echo "App $name does not exist"
	exit 1
fi

if [ ! -e $name/is_appts ]; then
	echo "App $name cannot be deleted"
	exit 1
fi

lxc-destroy -f -n $name
bin/fw-setup > /dev/null
